### PR TITLE
Nielsmeima/flatten chunk

### PR DESCRIPTION
**Pull request by nielsmeima**
@ncpenke I took a stab. Could you review this?

### CODE REVIEW

**Comment by ncpenke** [comment]
Looks amazing, thanks also for adding such thorough unit tests! I think just a few things needed to fix up the checks:

1. Run rust fmt `rust fmt --all`
2. Run clippy `cargo clippy --all --tests --fix`
3. Check that there aren't any compilation warnings (I think that's the the tests are failing).

Otherwise looks great!

**Comment by nielsmeima** [comment]
Code has been run through `fmt` and `clippy`. Remaining warning seems to originate from an unused lifetime in `deserialize.rs`. Also, a test in `tests/ui/struct_incorrect_type.rs` seems to be failing. However, both are outside the scope of changes of this PR.

**Comment by ncpenke** [comment]
Thanks for fixing up the formatting and clippy @nielsmeima. Taking a look at the warnings. `main` is successful so that's why thought the failures were related to these changes but could be something else.

**Comment by jorgecarleitao** [comment]
the new version of stable rust 1.62 landed yesterday which introduced new lints, so lint warnings are to be expected (almost everywhere in the ecosystem xD)

**Comment by ncpenke** [comment]
Thanks, I don't know how long it would've taken me to figure that out! Thanks for the great work @nielsmeima, merging this!

**Pull request merged**
