### PR TITLE
Split ArrowField derive macro

### PR DESCRIPTION
**Pull request by jondo2010**
This PR splits the ArrowField derive macro into separate macros for each derived trait.

Why: the previous undocumented container attributes to control which traits get implemented is not flexible enough. This way users have complete control over which trait gets generated.

### CODE REVIEW

**Comment by jondo2010** [comment]
Looks like CI hasn't run in a few months. I fixed everything here I think, which should also fix #89 if we land that after.

**Comment by ncpenke** [comment]
Thanks for fixing. main hasn't had changes since November, which is why CI hasn't run. We shifted development to a feature branch which requires rust 1.65 features. I'll rebase those changes on top of yours.

**Comment by ncpenke** [comment]
Looks like tests still failing, please let me know if you need help.

**Comment by jondo2010** [comment]
I guess we should bump the version as well since this is breaking :)

**Pull request merged**
